package CoreJavaPart2;

public class ExceptionDemo {
	public static void main(String[] args) {
		
		int a=4;
		int b=0;
		
		try {
			int k=a/b;
			
		}
		catch
		{
			System.out.println("I catched the error");
		}
	}
	
	
}
